### ISSUE TITLE
WC normalization in Flavio->EOS conversion

### ISSUE THREAD

**Issue by bednya** [wilson-eft/wilson#19]
According to documentation on [Flavio](https://wcxf.github.io/assets/pdf/WET.flavio.pdf) and [EOS](https://wcxf.github.io/assets/pdf/WET.EOS.pdf) bases, the wilson coefficient "CVLLt_bscc" in Flavio basis should be equal to "b->s::c2" in EOS (after Fiertz rearrangement).

However, I've got a factor of 2 difference, e.g, "CVLLt_bscc"=1 leads to
"b->s::c2"=1 after indirect conversion via Flavio->JMS->EOS.

```python
import flavio
import wilson
wcF = flavio.WilsonCoefficients()
wcF.set_initial(scale=3,wc_dict={'CVLL_bscc':0, 
                                 'CVLLt_bscc':1}
               )
wcF.wc.translate('JMS').translate('EOS')
```

<h3>WCxf Wilson coefficients</h3>

<table>
  <thead>
    <tr>
      <th>EFT</th>
      <th>Basis</th>
      <th>scale</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>WET</code></td>
      <td><code>EOS</code></td>
      <td>3.0 GeV</td>
    </tr>
  </tbody>
</table>
<h4>Values</h4>
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Re</th>
      <th>Im</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>b-&gt;s::c2</th>
      <td>0.5</td>
      <td>-1.734723e-18</td>
    </tr>
  </tbody>
</table>
</div>

**Comment by DavidMStraub** [comment]
Hi,

thanks for this report. Actually, just because the operators are the same doesn't mean the Wilson coefficents have to be the same since you have to invert the matrix translating the operator bases. Nevertheless I do think there is a factor of  two wrong there somewhere. @dvandyk and @jasonaebischerGIT, could you please have a look as well?

D

**Comment by DavidMStraub** [comment]
Thanks a lot for the checks. Yes, there does seem to be a mistake in the translations. It is a bit tedious to debug because, as currently implemented, there is another basis used as an intermediate step internally.

@jasonaebischerGIT and @dvandyk, I am extremely confident about the correctness of the Fierz/JMS/flavio translation functions as we scrutinized them a lot for the &epsilon;' project. So I suspect the error lies in the Fierz/EOS translation function.

**Comment by dvandyk** [comment]
Have to find time to look at this. @cBobeth might be interested to look as well.

**Comment by jasonaebischerGIT** [comment]
Dear all,
in the old version the implementation of the first two operators of the EOS basis was not correct, since I misunderstood the notation in the EOS Manual (eq. (5.6) in https://eos.github.io/manual/manual.pdf). I thought it to be a sum over the quark flavours u and c.  
I removed the two up-type operators and derived again the basis change, which should now be correct.

**Comment by DavidMStraub** [comment]
Thanks for fixing @jasonaebischerGIT!

Two final comments that the two of us realized in discussing this:
- EOS currently does not distinguish between NP in C<sub>1,2</sub> with up vs. charm flavour. This means that strictly speaking the operator they multiply is a linear combination of the up and charm operators weighted by CKM factors. In the translation, we actually neglect terms of order &lambda;<sub>u</sub>/&lambda;<sub>t</sub> as otherwise things would become very messy.
- Just a warning, note that when you translate from flavio to EOS, since the EOS basis is not complete, any linear combination of flavio WCs not matching onto an existing WC in EOS will "disappear" in the translation.
