### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by DavidMStraub** [wilson-eft/wilson#36]
@jasonaebischerGIT, @jackypheno, I would like to release a new version and I suggest to tag it 2.0 (given the major new feature of the 1-loop matching). Is there anything you still want me to wait for before tagging the release (e.g., #33)?

**Comment by jackypheno** [comment]
Dear David,

Please go ahead. I did not get chance to think on your comments on #33 . But I will do so eventually. 

Best regards,

**Comment by jasonaebischerGIT** [comment]
Thanks a lot for the work David! Very impressive!

**Comment by peterstangl** [comment]
If `wcxf-python` might be merged into `wilson` soon, this will probably be a new major version (at least if backward compatibility should be broken). Is it realistic to do this already for 2.0?

On the other hand, it might be possible to keep backward compatibility by merging `wcxf-python` into `wilson` such that `wilson` doesn't depend on `wcxf-python` anymore, but still keeping the standalone package `wcxf-python` (which will still depend on `wilson`). One just has to make sure that also older versions of `wcxf-python` can import their `wilson` dependencies without problems.
The `wcxf-python` package can then be turned into a kind of wrapper for the new parts of `wilson` that now contain the `wcxf-python` classes and functions.

Maybe the simplest way would be to just copy `wcxf-python` into a submodule of `wilson`. Instead of `import wcxf`, one could then just use `import wilson.wcxf` and the whole `wcxf-python` package (kept for backward compatibility) could look something like
```python
from wilson.wcxf import *
```

**Comment by DavidMStraub** [comment]
FYI, after merging the wcxf PR #37, I will add one more SMEFT translator (Higgs basis for the Higgs paper) and then plan to release 2.0, maybe tomorrow.

**Comment by DavidMStraub** [comment]
Done. Will release soon.
