### ISSUE TITLE
Discrepancy between Dekens/Stoffer and Wilson

### ISSUE THREAD

**Issue by tarendo** [wilson-eft/wilson#45]
When studying SMEFT influence on bs->mumu with @dvandyk we realized that the one-loop matching of certain four-fermion operators behaves differently in Wilson than in the Dekens/Stoffer mathematica code. Let us for example look at how the the SMEFT operator (in Warsaw Up basis) qq1 with indices (ii33) and (33ii) matches onto the WET operator (in JMS basis) VedLL with indices (2223).

According to Dekens/Stoffer the one-loop matching condition has the following form:
<img src="https://render.githubusercontent.com/render/math?math=f(m_t,m_W,m_Z,\mu_W,v)V_{i3}V^\dagger_{2i}*(Cqq1_{ttii}  %2B Cqq1_{iitt})">
where <img src="https://render.githubusercontent.com/render/math?math=f(m_t,m_W,m_Z,\mu_W,v)"> stands for a constant factor that does not depend on the indices, <img src="https://render.githubusercontent.com/render/math?math=V_{ik}"> is the CKM matrix and the index t stands for the top quark. So when setting <img src="https://render.githubusercontent.com/render/math?math=Cqq1_{ttii}  = Cqq1_{iitt} = 1"> for all i and when we sum over i=1,2,3 the whole contribution should cancel due to the unitarity of the CKM matrix.

We now repeat this exercise in Wilson where I understand that 'qq1_1133' is in fact qq1_1133+qq1_3311 (at least for real coefficients):
```
import wilson
wilson.Wilson.set_default_option('smeft_matching_order',1)
qq1_1133=wilson.Wilson({'qq1_1133':1},scale=91.1876,eft='SMEFT',basis='Warsaw up')
qq1_2233=wilson.Wilson({'qq1_2233':1},scale=91.1876,eft='SMEFT',basis='Warsaw up')
qq1_3333=wilson.Wilson({'qq1_3333':1},scale=91.1876,eft='SMEFT',basis='Warsaw up')

qq1_1133matched=qq1_1133.match_run(scale=91.1876,eft='WET',basis='JMS')['VedLL_2223']
qq1_2233matched=qq1_2233.match_run(scale=91.1876,eft='WET',basis='JMS')['VedLL_2223']
qq1_3333matched=qq1_3333.match_run(scale=91.1876,eft='WET',basis='JMS')['VedLL_2223']
print(qq1_1133matched)
print(qq1_2233matched)
print(qq1_3333matched,'\n')
print(qq1_1133matched+qq1_2233matched+qq1_3333matched)
print(qq1_1133matched+qq1_2233matched+qq1_3333matched/2.)
```

We see that here it is not actually the sum that vanishes but we have to devide qq1_3333matched by 2 in order for the contributions to cancel out.

**Comment by DavidMStraub** [comment]
Without looking at this in detail, I almost bet it is just a convention issue. Can you please look at appendix A.2 of https://arxiv.org/pdf/1810.07698.pdf and tell me if that solves your issue.

**Comment by dvandyk** [comment]
Dear @DavidMStraub, @peterstangl,

this is just to inform you that we are still looking into this. It's a bit puzzling to me.
The appendix that David provided clears up that in matching and running you switch
from the non-redundant basis to the redundant basis. This seems to be done in a 'symmetrize' function.

However, our problem appears to come from the operator with index 3333. In Dekens/Stoffer, this operators is seemingly contributing with a weight 2, since it appear as 'ii33 + 33ii', with i=3. In ```wilson``` it contributes with a weight 1, apparently. This is my hypothesis so far, and Sebastian and I will try to confirm it Tuesday.

**Comment by DavidMStraub** [comment]
The `qq1_1133` and `qq1_2233` coefficients differ by a factor 2 between the redundant and non-redundant conventions, while `qq1_3333` doesn't, so it makes total sense.

You should start with

```python
qq1_1133_nonredundant=wilson.Wilson({'qq1_1133':2},scale=91.1876,eft='SMEFT',basis='Warsaw up')
qq1_2233_nonredundant=wilson.Wilson({'qq1_2233':2},scale=91.1876,eft='SMEFT',basis='Warsaw up')
qq1_3333_nonredundant=wilson.Wilson({'qq1_3333':1},scale=91.1876,eft='SMEFT',basis='Warsaw up')
```

**Comment by dvandyk** [comment]
Thanks David, I had misunderstood the appendix. I had understood Wilson applied the symmetry factor internally before the matching (and was looking for it in the symmetrization functions), and removed it again after.

**Comment by DavidMStraub** [comment]
> I had understood Wilson applied the symmetry factor internally before the matching 

Yes, it is.

WCxf input: non-redundant basis.
Running: redundant (symmetrized) basis
WCxf output: non-redudant basis

My point was that the GIM cancellation mentioned by @tarendo holds in the redundant (symmetrized) basis, so to see it in Wilson, one has to start with 2-2-1 (in the non-redundant basis) rather than 1-1-1.

**Comment by dvandyk** [comment]
@DavidMStraub Thanks for your help, much appreciated!
